// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PFMA_Website.Data;

#nullable disable

namespace PFMA_Website.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240608131749_newMigrations")]
    partial class newMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("PFMA_Website.Model.Acteurs.Directs.Producteur", b =>
                {
                    b.Property<int>("ProducteurID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("contact")
                        .HasColumnType("TEXT");

                    b.Property<string>("localistation")
                        .HasColumnType("TEXT");

                    b.Property<string>("nom_op")
                        .HasColumnType("TEXT");

                    b.Property<string>("producteur_paddy_semences")
                        .HasColumnType("TEXT");

                    b.Property<string>("region")
                        .HasColumnType("TEXT");

                    b.Property<string>("site_internet")
                        .HasColumnType("TEXT");

                    b.Property<int>("superficie")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProducteurID");

                    b.ToTable("Producteurs");
                });

            modelBuilder.Entity("PFMA_Website.Model.Acteurs.Indirect.Vendeur", b =>
                {
                    b.Property<int>("VendeurID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("contact")
                        .HasColumnType("TEXT");

                    b.Property<string>("localistation")
                        .HasColumnType("TEXT");

                    b.Property<string>("nom_vendeur")
                        .HasColumnType("TEXT");

                    b.Property<string>("region")
                        .HasColumnType("TEXT");

                    b.Property<string>("site_internet")
                        .HasColumnType("TEXT");

                    b.Property<string>("type_intrants")
                        .HasColumnType("TEXT");

                    b.Property<int>("zone_intervention")
                        .HasColumnType("INTEGER");

                    b.HasKey("VendeurID");

                    b.ToTable("Vendeurs");
                });

            modelBuilder.Entity("PFMA_Website.Model.Actualite", b =>
                {
                    b.Property<int>("ActualiteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("tag")
                        .HasColumnType("TEXT");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ActualiteID");

                    b.ToTable("Actualites");
                });

            modelBuilder.Entity("PFMA_Website.Model.Descriptif", b =>
                {
                    b.Property<int>("DescriptifID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("tag")
                        .HasColumnType("TEXT");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DescriptifID");

                    b.ToTable("Descriptifs");
                });

            modelBuilder.Entity("PFMA_Website.Model.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
